//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DanismanlikEntities : DbContext
    {
        public DanismanlikEntities()
            : base("name=DanismanlikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<musteri_fatura_table> musteri_fatura_table { get; set; }
        public virtual DbSet<musteri_tanim_table> musteri_tanim_table { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
