//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteri_fatura_table
    {
        public int ID { get; set; }
        public Nullable<int> MUSTERI_ID { get; set; }
        public Nullable<System.DateTime> FATURA_TARIHI { get; set; }
        public Nullable<decimal> FATURA_TUTARI { get; set; }
        public Nullable<System.DateTime> ODEME_TARIHI { get; set; }
    }
}
